spring:
  data:
    redis:
      ##redis 单机环境配置
      # Redis服务器地址
      host: 127.0.0.1
      # Redis服务器连接端口
      port: 6379
      # Redis服务器连接密码（默认为空）
      #password: password
      # Redis数据库索引（默认为0）
      database: 0
      # 安全
      ssl:
        enabled: false
      # 连接超时时间（毫秒）
      timeout: 5000
      # 线程安全池
      lettuce:
        pool:
          # 连接池最大连接数(使用负值表示没有限制) 默认为8
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: 5000
          # 连接池中的最大空闲连接
          max-idle: 8
#         # 集群
#         cluster:
#           nodes:
#             - 10.18.80.14:6379
#             - 10.18.80.14:6380
#             - 10.18.80.14:6381
#             - 10.18.80.14:6382
#             - 10.18.80.14:6383
#             - 10.18.80.14:6384
#         # 哨兵
#        sentinel:
#          master: taybct
#          password: taybct2021
#          nodes: 192.168.0.10:36379,192.168.0.11:36380,192.168.0.12:36381,192.168.0.13:36382
#    session:
#      # 设置session保存为默认redis的方式
#      store-type: redis
#      redis:
#        # 命名空间
#        namespace: taybct